In [1]:
import numpy as np 
import pandas as pd

In [2]:
data=pd.read_table('http://archive.ics.uci.edu/ml/machine-learning-databases/00198/Faults.NNA', sep='\t', header=None)
data.head()

0     1        2        3     4   5    6       7   8    9  ...      24  \
0    42    50   270900   270944   267  17   44   24220  76  108 ...  0.8182   
1   645   651  2538079  2538108   108  10   30   11397  84  123 ...  0.7931   
2   829   835  1553913  1553931    71   8   19    7972  99  125 ...  0.6667   
3   853   860   369370   369415   176  13   45   18996  99  126 ...  0.8444   
4  1289  1306   498078   498335  2409  60  260  246930  37  126 ...  0.9338   

       25      26  27  28  29  30  31  32  33  
0 -0.2913  0.5822   1   0   0   0   0   0   0  
1 -0.1756  0.2984   1   0   0   0   0   0   0  
2 -0.1228  0.2150   1   0   0   0   0   0   0  
3 -0.1568  0.5212   1   0   0   0   0   0   0  
4 -0.1992  1.0000   1   0   0   0   0   0   0  

[5 rows x 34 columns]

In [3]:
data.shape

(1941, 34)

In [4]:
data_rand=data.sample(frac=1.0)

In [5]:
dvs=data_rand.iloc[:,27:]
dvs

27  28  29  30  31  32  33
1923   0   0   0   0   0   0   1
1732   0   0   0   0   0   0   1
1652   0   0   0   0   0   0   1
693    0   0   1   0   0   0   0
1248   0   0   0   0   0   1   0
1805   0   0   0   0   0   0   1
1813   0   0   0   0   0   0   1
1371   0   0   0   0   0   0   1
763    0   0   0   1   0   0   0
1232   0   0   0   0   0   1   0
386    0   0   1   0   0   0   0
598    0   0   1   0   0   0   0
764    0   0   0   1   0   0   0
1725   0   0   0   0   0   0   1
55     1   0   0   0   0   0   0
358    0   0   1   0   0   0   0
827    0   0   0   0   1   0   0
1534   0   0   0   0   0   0   1
1585   0   0   0   0   0   0   1
197    0   1   0   0   0   0   0
1572   0   0   0   0   0   0   1
887    0   0   0   0   0   1   0
61     1   0   0   0   0   0   0
419    0   0   1   0   0   0   0
750    0   0   0   1   0   0   0
331    0   1   0   0   0   0   0
1518   0   0   0   0   0   0   1
703    0   0   1   0   0   0   0
1053   0   0   0   0   0   1   0
1505   0   0   0   0   0   0   1
...   ..  ..  ..  ..  ..  ..  ..
200    0   1   0   0   0   0   0
1377   0   0   0   0   0   0   1
1921   0   0   0   0   0   0   1
1860   0   0   0   0   0   0   1
1357   0   0   0   0   0   0   1
1481   0   0   0   0   0   0   1
707    0   0   1   0   0   0   0
622    0   0   1   0   0   0   0
796    0   0   0   1   0   0   0
407    0   0   1   0   0   0   0
1439   0   0   0   0   0   0   1
1754   0   0   0   0   0   0   1
976    0   0   0   0   0   1   0
1061   0   0   0   0   0   1   0
1910   0   0   0   0   0   0   1
281    0   1   0   0   0   0   0
12     1   0   0   0   0   0   0
339    0   1   0   0   0   0   0
1075   0   0   0   0   0   1   0
395    0   0   1   0   0   0   0
287    0   1   0   0   0   0   0
1496   0   0   0   0   0   0   1
516    0   0   1   0   0   0   0
876    0   0   0   0   0   1   0
499    0   0   1   0   0   0   0
1015   0   0   0   0   0   1   0
1166   0   0   0   0   0   1   0
1163   0   0   0   0   0   1   0
1264   0   0   0   0   0   1   0
195    0   1   0   0   0   0   0

[1941 rows x 7 columns]

In [6]:
class_labels=dvs.idxmax(axis=1)

In [7]:
class_labels

1923    33
1732    33
1652    33
693     29
1248    32
1805    33
1813    33
1371    33
763     30
1232    32
386     29
598     29
764     30
1725    33
55      27
358     29
827     31
1534    33
1585    33
197     28
1572    33
887     32
61      27
419     29
750     30
331     28
1518    33
703     29
1053    32
1505    33
        ..
200     28
1377    33
1921    33
1860    33
1357    33
1481    33
707     29
622     29
796     30
407     29
1439    33
1754    33
976     32
1061    32
1910    33
281     28
12      27
339     28
1075    32
395     29
287     28
1496    33
516     29
876     32
499     29
1015    32
1166    32
1163    32
1264    32
195     28
Length: 1941, dtype: int64

In [8]:
IVs=data_rand.iloc[:,:27]
IVs.head()

0     1        2        3     4    5    6       7    8    9    ...    \
1923    23    43  2985008  2985026   170   42   20   19738  107  125   ...     
1732     9    19  1132780  1132795   117   11   15   12317   86  124   ...     
1652  1223  1235   456228   456249   193   19   21   19028   66  125   ...     
693     39   214  2886302  2886367  6182  295  138  635475   42  124   ...     
1248   701   717  7156447  7156460   147   20   13   16975  104  132   ...     

          17      18     19   20      21      22      23      24      25  \
1923  0.0147  0.4762  0.900  0.0  2.2304  1.3010  1.2553 -0.1000 -0.0929   
1732  0.0073  0.9091  1.000  1.0  2.0682  1.0000  1.1761  0.3333 -0.1776   
1652  0.0088  0.6316  1.000  1.0  2.2856  1.0792  1.3222  0.4286 -0.2298   
693   0.1291  0.5932  0.471  0.0  3.7911  2.2430  1.8129 -0.6286 -0.1969   
1248  0.0118  0.8000  1.000  0.0  2.1673  1.2041  1.1139 -0.1875 -0.0978   

          26  
1923  0.5951  
1732  0.2660  
1652  0.4170  
693   1.0000  
1248  0.3479  

[5 rows x 27 columns]

In [9]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier,BaggingClassifier, RandomForestClassifier
from sklearn.metrics import cohen_kappa_score, make_scorer


In [10]:
x_train, x_test, y_train, y_test= train_test_split(IVs,class_labels,test_size=0.2, random_state=123)

In [11]:
def kappa(y,y_pred, **kargs):
    return cohen_kappa_score(y,y_pred)

Kappa= make_scorer(kappa)

In [12]:
tree=DecisionTreeClassifier()
rf=RandomForestClassifier()
bagg=BaggingClassifier(base_estimator=tree)
boost=AdaBoostClassifier(base_estimator=tree)

In [21]:
param_grid_tree={'criterion':['gini','entropy'],'max_depth':[3,5,7,9]}
param_grid_rf={'n_estimators':[100,200,500],'max_depth':[3,5,7,9]}
param_grid_bagg={'n_estimators':[100,200,500]}
param_grid_boost={'n_estimators':[100,200,500],'learning_rate':[0.0001,0.0003,0.0005]}

In [22]:
best_model_tree=GridSearchCV(estimator=tree,param_grid=param_grid_tree,scoring=Kappa,cv=5)
best_model_rf=GridSearchCV(estimator=rf,param_grid=param_grid_rf,scoring=Kappa,cv=5)
best_model_bagg=GridSearchCV(estimator=bagg,param_grid=param_grid_bagg,scoring=Kappa,cv=5)
best_model_boost=GridSearchCV(estimator=boost,param_grid=param_grid_boost,scoring=Kappa,cv=5)


In [23]:
best_model_tree.fit(X=x_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'criterion': ['gini', 'entropy'], 'max_depth': [3, 5, 7, 9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [24]:
best_model_tree.best_params_

{'criterion': 'entropy', 'max_depth': 9}

In [25]:
cross_val_score(best_model_tree.best_estimator_,X=x_train,y=y_train,cv=5)

array([0.7388535 , 0.7       , 0.72580645, 0.72168285, 0.71197411])

In [26]:
best_model_rf.fit(X=x_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [100, 200, 500], 'max_depth': [3, 5, 7, 9]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [28]:
best_model_rf.best_params_

{'max_depth': 9, 'n_estimators': 100}

In [29]:
cross_val_score(best_model_rf.best_estimator_,X=x_train,y=y_train,cv=5)

array([0.79936306, 0.75483871, 0.77096774, 0.72815534, 0.72168285])

In [27]:
best_model_bagg.fit(X=x_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            ...n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [100, 200, 500]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [30]:
best_model_bagg.best_params_

{'n_estimators': 200}

In [31]:
cross_val_score(best_model_bagg.best_estimator_,X=x_train,y=y_train,cv=5)

array([0.79936306, 0.78064516, 0.8       , 0.76699029, 0.76699029])

In [32]:
best_model_boost.fit(X=x_train,y=y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=50, random_state=None),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [100, 200, 500], 'learning_rate': [0.0001, 0.0003, 0.0005]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=make_scorer(kappa), verbose=0)

In [33]:
best_model_boost.best_params_

{'learning_rate': 0.0001, 'n_estimators': 200}

In [34]:
cross_val_score(best_model_boost.best_estimator_,X=x_train,y=y_train,cv=5)

array([0.72611465, 0.69354839, 0.68387097, 0.71197411, 0.66666667])